 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default

     steps:
       - checkout
       - run: dotnet build
       - run: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
       - run:
          name: "Print Working Directory"
          command: pwd
       - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
